-- Enable Row Level Security (RLS) on all Supabase Database Tables (Default Deny)

ALTER TABLE IF EXISTS "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Leaderboard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "VerificationCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "PracticeSession" ENABLE ROW LEVEL SECURITY;
